spring:
  application:
    name: service-transport
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  otlp:
    metrics:
      export:
        url: ${OTLP_URL:http://localhost:4318/v1/metrics}
        step: 10s

logging:
  loki:
    url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
  level:
    com.danburn: DEBUG
